### ISSUE TITLE
New contributor

### ISSUE THREAD

**Issue by pneerincx** [fgeorgatos/easybuild.experimental#11]
Hi EasyBuild experimentalists,

I'm working at the University Medical Center Groningen (UMCG) and would like to contribute to this repo; Can you please add https://github.com/pneerincx

Cheers,

Pi

**Comment by fgeorgatos** [comment]
Hi Pieter!

try to clone the repo, add users/pneerincx subdirectory and contribute back. 
If this puzzles you, would you be willing to meet on irc and sort it out?

**Comment by fgeorgatos** [comment]
OK, you are now a collaborator of the repo; mea culpa for not having it working earlier ;-)
